# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-07 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0006_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='producti',
            new_name='productid',
        ),
    ]
