# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-09 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.CharField(default='touxiang.jpg', max_length=40),
        ),
    ]
